FROM nginx

RUN cp /etc/apt/sources.list /etc/apt/sources.list.bak && \
    echo "deb http://mirrors.163.com/debian/ jessie main non-free contrib" >/etc/apt/sources.list && \
    echo "deb http://mirrors.163.com/debian/ jessie-proposed-updates main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb-src http://mirrors.163.com/debian/ jessie main non-free contrib" >>/etc/apt/sources.list && \
    echo "deb-src http://mirrors.163.com/debian/ jessie-proposed-updates main non-free contrib" >>/etc/apt/sources.list

RUN apt-get update -qq && apt-get -y install apache2-utils vim

ENV RAILS_ROOT /var/www/cuit_acm

WORKDIR $RAILS_ROOT

RUN mkdir log

COPY public public/

COPY config/acm_nginx.conf /tmp/acm_nginx.conf

RUN envsubst '$RAILS_ROOT' < /tmp/acm_nginx.conf > /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD [ "nginx", "-g", "daemon off;" ]

