
default: &default
  app_ns: 'cuit_acm'
  achieve_mq: 'achievement_queue'


development:
  <<: *default
  host: '127.0.0.1'
  port: 6379
  db: 0
  time_out: 0.12

production:
  <<: *default
  host: <%= ENV['REDIS_HOST'] %>
  port: 6379
  db: 0
  time_out: 0.12